services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      custom_net:
        ipv4_address: ${DB_HOST}

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./src/main/resources/db/changelog:/changelog
    command: --changeLogFile=/changelog/changelog.yml --url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} --username=${DB_USER} --password=${DB_PASS} ${LB_COMMAND}
    networks:
      custom_net:
        ipv4_address: ${LB_HOST}
    depends_on:
      - db

volumes:
  db_data:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
