services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data

#    networks:
#      custom_net:
#        ipv4_address: ${DB_HOST}

  # Имедж liquibase поднимать необязательно, его можно просто подключить как зависимость к проекту и он при старте приложения накатит миграции
  # https://contribute.liquibase.com/extensions-integrations/directory/integration-docs/springboot/using-springboot-with-gradle/
  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./src/main/resources/db/changelog:/changelog
    command: --changeLogFile=/changelog/changelog.yml --url=jdbc:postgresql://db:${DB_PORT}/${DB_NAME} --username=${DB_USER} --password=${DB_PASS} ${LB_COMMAND}
#    command: tail -f /dev/null


    depends_on:
      - db

#  keycloak:
#    image: quay.io/keycloak/keycloak
#    environment:
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
#      KC_DB_USERNAME: keycloak
#      KC_DB_PASSWORD: password
#
#      KC_HOSTNAME: localhost
#      KC_HOSTNAME_PORT: 8080
#
#      KC_LOG_LEVEL: info
#      KC_HOSTNAME_STRICT: false
#      KEYCLOAK_PROXY: edge
#      KC_HTTP_ENABLED: true
#      KC_HOSTNAME_STRICT_HTTPS: false
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    command: start-dev
#    depends_on:
#      - keycloakdb
#    ports:
#      - 8080:8080

#  keycloakdb:
#    image: postgres
#    volumes:
#      - keycloak_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - 6379:6379

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db_data:
#  keycloak_data:

