logging:
  level:
    root: DEBUG

spring:
  application:
    name: url_shortener
  security:
#    oauth2:
#      client:
#        registration:
#          my-oauth2-client:
#            provider: keycloak
#            client-id: url_shortener
#            client-secret: tYhss3CmeFqDuoR76croI19LJ4HgUmBT
#            authorization-grant-type: authorization_code
#            scope: openid, profile
#            redirect-uri: http://localhost:8888/home
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/url_shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypass

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
    url: jdbc:postgresql://localhost:5432/mydatabase
    user: myuser
    password: mypass

  jpa:
    #Debug
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: validate

  redis:
    host: localhost
    port: 6379


server:
  port:
    8888
#TODO
#  ssl:
#    enabled: true

settings:
  HostConfig:
    PROTOCOL: http
    HOST: localhost


  ShortUrlConfig:
    SIZE: 5

  LongUrlConfig:
    SIZE_LOWER_BOUND: 3
    SIZE_UPPER_BOUND: 2048

  LoginConfig:
    SIZE_LOWER_BOUND: 1
    SIZE_UPPER_BOUND: 36

  PasswordConfig:
    SIZE_LOWER_BOUND: 8
    SIZE_UPPER_BOUND: 254

  EmailConfig:
    SIZE_LOWER_BOUND: 1
    SIZE_UPPER_BOUND: 254