logging:
  level:
    root: DEBUG

spring:
  application:
    name: url_shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypass
  liquibase:
    enabled: true
    # Не увидел где лежат миграции
    change-log: classpath:db/changelog/changelog-master.yaml
  jpa:
    #Debug
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create-drop

settings:
  HostConfig:
    PROTOCOL: http
    HOST: localhost
    PORT: 8080

  ShortUrlConfig:
    SIZE: 5

  LongUrlConfig:
    SIZE_LOWER_BOUND: 3
    SIZE_UPPER_BOUND: 2048

  LoginConfig:
    SIZE_LOWER_BOUND: 1
    SIZE_UPPER_BOUND: 36

  PasswordConfig:
    SIZE_LOWER_BOUND: 8
    SIZE_UPPER_BOUND: 254

  EmailConfig:
    SIZE_LOWER_BOUND: 1
    SIZE_UPPER_BOUND: 254